### ISSUE TITLE
switching between thumbnail and image

### ISSUE THREAD

**Issue by diegopau** [Darknior/RVGM-BT-Theme#1]
Hi. First of all thanks for this wonderful theme.

This is not really an issue but much of a question. In my ROM collection my images are organized like this:
- image: the boxart
- thumbnail: the screenshot of the game which i want to show if the video is not available
- video.

I was using retropie before with your previous theme https://github.com/Darknior/RVGM-ES-Theme
When migrating from retropie to retrobat (which is compatible with batocera) I noticed that somehow batocera new theme format inverts image and thumbnail: so where I was seeing the boxart now I was seeing the thumbnail and othe other way around. This is explained in this image: https://www.dropbox.com/s/sfylr9exeqcfche/es_rb.png?dl=0

In your BT theme I also was seeing the problem, for some time I thought I would need to re-scrape the whole ROM collection. But then I saw in your theme somehow you also had this problem? I see code about switching from md_image to md_thumbnail and I would like to know how it works. All i know is that if I use the "video" view, my favorite one, all I have to do is to change this:

    
        <image name="md_thumbnail">
	    <pos>0.0255 0.0639</pos>
	    <maxSize>0.3766 0.6689</maxSize>
        </image>

to this

     
	<image name="**md_image**">
		<pos>0.0255 0.0639</pos>
		<maxSize>0.3766 0.6689</maxSize>
	</image>`

but that doesn't seem to be the whole story, because I tried to edit my own simple theme and when I use "md_image" is still taking the images defined in the thumbnail tag of my gamelist.xml. Then I noticed that in your theme.xml you also have this:

     <view name="basic, detailed, video">
  	
	<image name="md_image">
		<origin>0 0</origin>
		<pos>2 2</pos>
		<default>${artPath}/empty.png</default>
		<zIndex>30</zIndex> 
	</image>
	<image name="md_thumbnail">
		<origin>0 0</origin>
		<pos>2 2</pos>
		<default>${artPath}/empty.png</default>
		<zIndex>30</zIndex> 
	</image>

and that if that wasn't there then I would not be able to use "md_image" to show the boxart (what I have in the image tag of my gamelist.xml) in the video view.

So my questions are: is that the standard way of doing it? is Batocera breaking compatibility with retropie themes because the way it handles md_image ? what is the right way to scrape the roms for your theme?? I would love to have a scrapped collection that works both in batocera and retropie, but not sure if it is possible.. and also to understand how theming works... in my opinion it would made sense that if you use md_image then the image tag of the gamelist.xml is used...

**Comment by diegopau** [comment]
Ok, I understood now, the view used matter. When using video view it takes the thumbnail as md_image for some reason, but if I use view detailed then md_image has the behavior I wanted. You can ignore this whole thing...

**Comment by Darknior** [comment]
Hi
I came from Retropie like you and go to Batocera because i really prefer it.
Like you i discover this problem, we speak a lot with @f.caruso of this problem and decide to use these settings to make ES compatible with most of the ES theme made for Retropie and Recallbox.

At first i'va add a switch option, to switch IMAGE and THUMBNAIL to not scrap again my gamelist.
But now it doesn't works fine with the new CUSTOMVIEW in ES, it made some bugs and last night i remove this option and fix the images like in this exemple :

> <image>./../../medias/virtualboy/titleshots/Hyper Fighting (USA) (Unl).jpg</image>
> <marquee>./../../medias/virtualboy/logos/Hyper Fighting (USA) (Unl).png</marquee>
> <video>./../../medias/virtualboy/videos/Hyper Fighting (USA) (Unl).mp4</video>
> <thumbnail>./../../medias/virtualboy/box front/Hyper Fighting (USA) (Unl).jpg</thumbnail>

And i modify all my games list from a long time, it's easy and fast with CTRL+H

Replace : `<thumbnail>./../../medias/virtualboy/titleshots/`
By : `<thumbnail>./../../medias/virtualboy/box front/`

Really don't modify the **theme**, modify **gamelist**.
I update the theme almost every days from some month ... a really BIG BIG BIG update come this night or tomorrow ... that will some bugs and improve text a lot ...

If you want to have all informations, you can read them there : 
https://www.facebook.com/Retro-Video-Game-Museum-RVGM-100474828146801/

And i also make some videos for big updates there : 
https://www.youtube.com/user/HuguesFabien/videos?view_as=subscriber

Some new videos come in a few days ... ;)
Let the issue open, maybe it can help some other users to read it ;)

PS : Next update will let every one help me to correct and fix text errors, if you read some ... please report me some fix here...

**Comment by diegopau** [comment]
If keeping those settings help keeping compatibility with other ES themes for Retropie and Recallbox I think it was a good decision! I think it is good that different ES software can be at least a bit compatible so people can switch from one to another easily :)

Alright, I think I will modify all my gamelists then, it will not be a lot of work.

Looking forward to your udpates! I only found 3 systems that I have some roms and your theme doesn't include: Philips CD-I, BBC micro and n64DD... i know, very strange systems!

If I find any text errors I will let you know. I speak Spanish and have decent English! Thanks!! I think you can close the issue now.

**Comment by Darknior** [comment]
`Philips CD-I, BBC micro and n64DD` are not included in Batocera and i don't made them for now.
- Philips CDI ... i play it for real when i was young, there is noting on it lol
- BBC Micro i don't know
- N64DD is an aborted project, no many games on it, nothing really interesting for sure. The only good Hack for it is a Zelda add on to add a new quest. But not intesting too because you can found it in N64 ROM Hack, easier to play and use :)

I will update some systems i want to draw better, and add some collections too :)

So cool i don't speak Spanish :( I use Google trad to translate the theme, with the next update you will can help me if you want to correct texts and menu :)

**Comment by diegopau** [comment]
@Darknior hello! how is that new big update going? Usually I don't have much free time to enjoy my hobbies but finally the next week I will have some vacation days from work so I would like to review the Spanish translations. Will you add more spanish texts or should I review the ones that I see already in https://github.com/Darknior/RVGM-BT-Theme/blob/master/_Ressources/descriptions sp.txt ?

**Comment by Darknior** [comment]
@diegopau hi :)
This file was my first idea to share texts to help users to help me to translate my theme. But in next release you will can directly translate all the text in XML files, it will be a great update !!!
I try to make it available this week,  i work on it every day. 
Many text are Google translated, it will be really better if you correct all of them :)

**Comment by diegopau** [comment]
Awesome! I will wait for that then :)

**Comment by Darknior** [comment]
> 

Hi, i have updated the theme with a lot of systems like CDi, BBS, etc .... in french, and with a google translate for english.
So users have help me to fix some english text. If you want to verify them, or add them in spanish, now you can send them :)
Thanks

**Comment by Darknior** [comment]
Removed option, with time now it is a non used option
