### ISSUE TITLE
Nintendo switch integration

### ISSUE THREAD

**Issue by wadiebs** [Darknior/RVGM-BT-Theme#29]
Hello,
I really like this skin!
Could you please check if possible to add nintendo switch
Thank you

**Comment by Darknior** [comment]
Hello thanks a lot
Switch is already included, not finished because a lak of time ... but included with a draw of Monster Hunter something like it.
If you don't see it it is because your directory has a bad name, the me is made for Batocera and Retrobat.
For the moment i have not many time to work on the theme i will not add many new systems ...

**Comment by wadiebs** [comment]
Thank you for your feedback, I tested it yesterday, the logo and the first screen are fine, but the game browsing page is not accurate, the list of game is there but no game info no video, only game screenshot is shown.

**Comment by Darknior** [comment]
Be cause you have choose a bad view, all is fine here, the problem is on your settings. use the view video.
All systemes are working same, if the logo is there all is there. i don't made a different game browsing page for each system.
