### ISSUE TITLE
Stuttering in video previews halfway through

### ISSUE THREAD

**Issue by Tasosgemah** [Darknior/RVGM-BT-Theme#50]
When i use this theme, sometimes the video previews stutter/lag very intensely. 

They start smooth but stutter after 10 or so seconds.

It doesn't happen all the time but it's very often, if i switch games around it happens 90% of the time.

This doesn't happen with other themes.

**Comment by Darknior** [comment]
Hi, i can't help you, theme is only a design interface, nothing more.
Your bug come from ES engine or come from your material :(
I know my theme is slow on PI3 because so many images are using so many memory RAM !
I will try one day to add an option to make it more compatible with little boards but it is a long and hard work :(

**Comment by Tasosgemah** [comment]
I have a PC, not a Pi, so performance isn't an issue.

You were right though, it wasn't a theme related issue. It was the "power saving" setting in ES being enabled by default.

I have no idea why it only affected this particular theme though.

**Comment by Darknior** [comment]
I don't know why, but for sure the author of Es tell me to not use it. It is not working fine, it is an old feature for little boards.
